---
abstract: 'Provide a gather keyword'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
  - 'Damian Conway'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Feature-Gather
requires:
  Sub::Exporter: 0.986
  Syntax::Keyword::Gather: 1.002000
  Test::More: 0.94
  syntax: 0.002
resources:
  bugtracker: https://github.com/frioux/Syntax-Feature-Gather/issues
  repository: git://github.com/frioux/Syntax-Feature-Gather.git
version: 1.002001
